-- MySQL Script generated by MySQL Workbench
-- 08/12/15 08:57:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chatbot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatbot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatbot` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
-- -----------------------------------------------------
-- Schema ebdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ebdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebdb` DEFAULT CHARACTER SET latin1 ;
USE `chatbot` ;

-- -----------------------------------------------------
-- Table `chatbot`.`topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`topics` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`topics` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `topic_name` VARCHAR(255) NOT NULL,
  `rank` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_TopicName` (`topic_name` ASC),
  INDEX `index_topic_name` USING BTREE (`topic_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`rules` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`rules` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `topic_id` INT(19) NULL DEFAULT NULL,
  `rule_name` VARCHAR(255) NOT NULL,
  `rank` INT(11) NULL DEFAULT NULL,
  `response` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_RuleName` (`topic_id` ASC, `rule_name` ASC),
  CONSTRAINT `rules_ibfk_1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `chatbot`.`topics` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 895
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`actions` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`actions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `rule_id` INT(19) NULL DEFAULT NULL,
  `action_body` TEXT NOT NULL,
  `priority` INT(19) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rule_id` (`rule_id` ASC),
  FULLTEXT INDEX `index_actions_action_body` (`action_body` ASC),
  CONSTRAINT `actions_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `chatbot`.`rules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`chatbots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`chatbots` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`chatbots` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `chatbot_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_ChatbotName` (`chatbot_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`inputs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`inputs` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`inputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `rule_id` INT(19) NULL DEFAULT NULL,
  `input_text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rule_id` (`rule_id` ASC),
  CONSTRAINT `inputs_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `chatbot`.`rules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1337
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`outputs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`outputs` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`outputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `rule_id` INT(19) NULL DEFAULT NULL,
  `output_text` TEXT NOT NULL,
  `request` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rule_id` (`rule_id` ASC),
  FULLTEXT INDEX `index_outputs` (`output_text` ASC),
  CONSTRAINT `outputs_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `chatbot`.`rules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 897
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`queries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`queries` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`queries` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `query_text` TEXT NOT NULL,
  `session_id` VARCHAR(255) NULL DEFAULT NULL,
  `chatbot_name` VARCHAR(255) NULL DEFAULT NULL,
  `event_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `response` TEXT NULL DEFAULT NULL,
  `actions` TEXT NULL DEFAULT NULL,
  `request` VARCHAR(255) NULL DEFAULT NULL,
  `rule_id` INT(19) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_queries_session_chatbot` USING BTREE (`session_id` ASC, `chatbot_name` ASC),
  INDEX `index_queries_session` USING BTREE (`session_id` ASC),
  INDEX `index_queries_rule_id` USING BTREE (`rule_id` ASC),
  FULLTEXT INDEX `index_query_text` (`query_text` ASC),
  FULLTEXT INDEX `index_query_response` (`response` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`state_machines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`state_machines` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`state_machines` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `state_machine_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_StateMachineName` (`state_machine_name` ASC),
  INDEX `index_state_machine_name` USING BTREE (`state_machine_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`sm_actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`sm_actions` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`sm_actions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `state_machine_id` INT(19) NOT NULL,
  `sm_action_name` VARCHAR(255) NOT NULL,
  `action_text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMActionName` (`state_machine_id` ASC, `sm_action_name` ASC),
  CONSTRAINT `sm_actions_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `chatbot`.`state_machines` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`sm_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`sm_rules` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`sm_rules` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `state_machine_id` INT(19) NOT NULL,
  `sm_rule_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMRuleName` (`state_machine_id` ASC, `sm_rule_name` ASC),
  CONSTRAINT `sm_rules_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `chatbot`.`state_machines` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`sm_actions_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`sm_actions_rules` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`sm_actions_rules` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `sm_rule_id` INT(19) NOT NULL,
  `sm_action_id` INT(19) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMActionRuleRecord` (`sm_rule_id` ASC, `sm_action_id` ASC),
  INDEX `sm_action_id` (`sm_action_id` ASC),
  CONSTRAINT `sm_actions_rules_ibfk_1`
    FOREIGN KEY (`sm_rule_id`)
    REFERENCES `chatbot`.`sm_rules` (`id`),
  CONSTRAINT `sm_actions_rules_ibfk_2`
    FOREIGN KEY (`sm_action_id`)
    REFERENCES `chatbot`.`sm_actions` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`sm_variables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`sm_variables` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`sm_variables` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `state_machine_id` INT(19) NOT NULL,
  `sm_variable_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMVariableName` (`state_machine_id` ASC, `sm_variable_name` ASC),
  CONSTRAINT `sm_variables_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `chatbot`.`state_machines` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 120
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`sm_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`sm_conditions` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`sm_conditions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `sm_rule_id` INT(19) NOT NULL,
  `sm_variable_id` INT(19) NOT NULL,
  `sm_variable_value` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMConditionName` (`sm_rule_id` ASC, `sm_variable_id` ASC),
  INDEX `index_sm_conditions_matching` USING BTREE (`sm_variable_id` ASC, `sm_variable_value` ASC),
  CONSTRAINT `sm_conditions_ibfk_1`
    FOREIGN KEY (`sm_rule_id`)
    REFERENCES `chatbot`.`sm_rules` (`id`),
  CONSTRAINT `sm_conditions_ibfk_2`
    FOREIGN KEY (`sm_variable_id`)
    REFERENCES `chatbot`.`sm_variables` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 424
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`sm_memory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`sm_memory` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`sm_memory` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `session_id` VARCHAR(255) NOT NULL,
  `state_machine_id` INT(19) NOT NULL,
  `sm_variable_name` VARCHAR(255) NOT NULL,
  `sm_variable_value` TINYINT(1) NOT NULL,
  `sm_last_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMMemoryRecord` (`session_id` ASC, `state_machine_id` ASC, `sm_variable_name` ASC),
  INDEX `index_sm_memory_matching` USING BTREE (`session_id` ASC, `state_machine_id` ASC, `sm_variable_name` ASC, `sm_variable_value` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`split_inputs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`split_inputs` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`split_inputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `input_id` INT(19) NOT NULL,
  `prev_word` VARCHAR(255) NULL DEFAULT NULL,
  `word` VARCHAR(255) NOT NULL,
  `next_word` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_split_inputs_InputID` USING BTREE (`input_id` ASC),
  INDEX `index_split_inputs_word_word` USING BTREE (`word` ASC),
  INDEX `index_split_inputs_word_triplet` USING BTREE (`prev_word` ASC, `word` ASC, `next_word` ASC),
  CONSTRAINT `split_inputs_ibfk_1`
    FOREIGN KEY (`input_id`)
    REFERENCES `chatbot`.`inputs` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30920
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`split_queries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`split_queries` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`split_queries` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `query_id` INT(19) NULL DEFAULT NULL,
  `prev_word` VARCHAR(255) NULL DEFAULT NULL,
  `word` VARCHAR(255) NULL DEFAULT NULL,
  `next_word` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `query_id` (`query_id` ASC),
  CONSTRAINT `split_queries_ibfk_1`
    FOREIGN KEY (`query_id`)
    REFERENCES `chatbot`.`queries` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 129
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`topics_chatbots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`topics_chatbots` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`topics_chatbots` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `topic_id` INT(19) NOT NULL,
  `chatbot_id` INT(19) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `topic_id` (`topic_id` ASC),
  INDEX `chatbot_id` (`chatbot_id` ASC),
  CONSTRAINT `topics_chatbots_ibfk_1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `chatbot`.`topics` (`id`),
  CONSTRAINT `topics_chatbots_ibfk_2`
    FOREIGN KEY (`chatbot_id`)
    REFERENCES `chatbot`.`chatbots` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot`.`words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatbot`.`words` ;

CREATE TABLE IF NOT EXISTS `chatbot`.`words` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `syn_to_id` INT(19) NULL DEFAULT NULL,
  `word` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `syn_to_id` (`syn_to_id` ASC),
  CONSTRAINT `words_ibfk_1`
    FOREIGN KEY (`syn_to_id`)
    REFERENCES `chatbot`.`words` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `ebdb` ;

-- -----------------------------------------------------
-- Table `ebdb`.`topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`topics` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`topics` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `topic_name` VARCHAR(255) NOT NULL,
  `rank` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_TopicName` (`topic_name` ASC),
  INDEX `index_topic_name` USING BTREE (`topic_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`rules` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`rules` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `topic_id` INT(19) NULL DEFAULT NULL,
  `rule_name` VARCHAR(255) NOT NULL,
  `rank` INT(11) NULL DEFAULT NULL,
  `response` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_RuleName` (`topic_id` ASC, `rule_name` ASC),
  CONSTRAINT `rules_ibfk_1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `ebdb`.`topics` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 879
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`actions` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`actions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `rule_id` INT(19) NULL DEFAULT NULL,
  `action_body` TEXT NOT NULL,
  `priority` INT(19) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rule_id` (`rule_id` ASC),
  FULLTEXT INDEX `index_actions_action_body` (`action_body` ASC),
  CONSTRAINT `actions_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `ebdb`.`rules` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`chatbots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`chatbots` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`chatbots` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `chatbot_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_ChatbotName` (`chatbot_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`inputs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`inputs` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`inputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `rule_id` INT(19) NULL DEFAULT NULL,
  `input_text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rule_id` (`rule_id` ASC),
  CONSTRAINT `inputs_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `ebdb`.`rules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1311
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`outputs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`outputs` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`outputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `rule_id` INT(19) NULL DEFAULT NULL,
  `output_text` TEXT NOT NULL,
  `request` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rule_id` (`rule_id` ASC),
  FULLTEXT INDEX `index_outputs` (`output_text` ASC),
  CONSTRAINT `outputs_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `ebdb`.`rules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 879
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`queries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`queries` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`queries` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `query_text` TEXT NOT NULL,
  `session_id` VARCHAR(255) NULL DEFAULT NULL,
  `chatbot_name` VARCHAR(255) NULL DEFAULT NULL,
  `event_date` TIMESTAMP NULL DEFAULT NULL,
  `response` TEXT NULL DEFAULT NULL,
  `actions` TEXT NULL DEFAULT NULL,
  `request` VARCHAR(255) NULL DEFAULT NULL,
  `rule_id` INT(19) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_queries_session_chatbot` USING BTREE (`session_id` ASC, `chatbot_name` ASC),
  INDEX `index_queries_session` USING BTREE (`session_id` ASC),
  INDEX `index_queries_rule_id` USING BTREE (`rule_id` ASC),
  FULLTEXT INDEX `index_query_text` (`query_text` ASC),
  FULLTEXT INDEX `index_query_response` (`response` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`state_machines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`state_machines` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`state_machines` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `state_machine_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_StateMachineName` (`state_machine_name` ASC),
  INDEX `index_state_machine_name` USING BTREE (`state_machine_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`sm_actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`sm_actions` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`sm_actions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `state_machine_id` INT(19) NOT NULL,
  `sm_action_name` VARCHAR(255) NOT NULL,
  `action_text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMActionName` (`state_machine_id` ASC, `sm_action_name` ASC),
  CONSTRAINT `sm_actions_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `ebdb`.`state_machines` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`sm_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`sm_rules` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`sm_rules` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `state_machine_id` INT(19) NOT NULL,
  `sm_rule_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMRuleName` (`state_machine_id` ASC, `sm_rule_name` ASC),
  CONSTRAINT `sm_rules_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `ebdb`.`state_machines` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`sm_actions_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`sm_actions_rules` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`sm_actions_rules` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `sm_rule_id` INT(19) NOT NULL,
  `sm_action_id` INT(19) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMActionRuleRecord` (`sm_rule_id` ASC, `sm_action_id` ASC),
  INDEX `sm_action_id` (`sm_action_id` ASC),
  CONSTRAINT `sm_actions_rules_ibfk_1`
    FOREIGN KEY (`sm_rule_id`)
    REFERENCES `ebdb`.`sm_rules` (`id`),
  CONSTRAINT `sm_actions_rules_ibfk_2`
    FOREIGN KEY (`sm_action_id`)
    REFERENCES `ebdb`.`sm_actions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`sm_variables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`sm_variables` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`sm_variables` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `state_machine_id` INT(19) NOT NULL,
  `sm_variable_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMVariableName` (`state_machine_id` ASC, `sm_variable_name` ASC),
  CONSTRAINT `sm_variables_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `ebdb`.`state_machines` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`sm_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`sm_conditions` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`sm_conditions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `sm_rule_id` INT(19) NOT NULL,
  `sm_variable_id` INT(19) NOT NULL,
  `sm_variable_value` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMConditionName` (`sm_rule_id` ASC, `sm_variable_id` ASC),
  INDEX `index_sm_conditions_matching` USING BTREE (`sm_variable_id` ASC, `sm_variable_value` ASC),
  CONSTRAINT `sm_conditions_ibfk_1`
    FOREIGN KEY (`sm_rule_id`)
    REFERENCES `ebdb`.`sm_rules` (`id`),
  CONSTRAINT `sm_conditions_ibfk_2`
    FOREIGN KEY (`sm_variable_id`)
    REFERENCES `ebdb`.`sm_variables` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`sm_memory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`sm_memory` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`sm_memory` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `session_id` VARCHAR(255) NOT NULL,
  `state_machine_id` INT(19) NOT NULL,
  `sm_variable_name` VARCHAR(255) NOT NULL,
  `sm_variable_value` TINYINT(1) NOT NULL,
  `sm_last_modified` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uc_SMMemoryRecord` (`session_id` ASC, `state_machine_id` ASC, `sm_variable_name` ASC),
  INDEX `index_sm_memory_matching` USING BTREE (`session_id` ASC, `state_machine_id` ASC, `sm_variable_name` ASC, `sm_variable_value` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`split_inputs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`split_inputs` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`split_inputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `input_id` INT(19) NOT NULL,
  `prev_word` VARCHAR(255) NULL DEFAULT NULL,
  `word` VARCHAR(255) NOT NULL,
  `next_word` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_split_inputs_InputID` USING BTREE (`input_id` ASC),
  INDEX `index_split_inputs_word_word` USING BTREE (`word` ASC),
  INDEX `index_split_inputs_word_triplet` USING BTREE (`prev_word` ASC, `word` ASC, `next_word` ASC),
  CONSTRAINT `split_inputs_ibfk_1`
    FOREIGN KEY (`input_id`)
    REFERENCES `ebdb`.`inputs` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30880
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`split_queries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`split_queries` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`split_queries` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `query_id` INT(19) NULL DEFAULT NULL,
  `prev_word` VARCHAR(255) NULL DEFAULT NULL,
  `word` VARCHAR(255) NULL DEFAULT NULL,
  `next_word` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `query_id` (`query_id` ASC),
  CONSTRAINT `split_queries_ibfk_1`
    FOREIGN KEY (`query_id`)
    REFERENCES `ebdb`.`queries` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 75
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`topics_chatbots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`topics_chatbots` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`topics_chatbots` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `topic_id` INT(19) NOT NULL,
  `chatbot_id` INT(19) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `topic_id` (`topic_id` ASC),
  INDEX `chatbot_id` (`chatbot_id` ASC),
  CONSTRAINT `topics_chatbots_ibfk_1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `ebdb`.`topics` (`id`),
  CONSTRAINT `topics_chatbots_ibfk_2`
    FOREIGN KEY (`chatbot_id`)
    REFERENCES `ebdb`.`chatbots` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ebdb`.`words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebdb`.`words` ;

CREATE TABLE IF NOT EXISTS `ebdb`.`words` (
  `id` INT(19) NOT NULL AUTO_INCREMENT,
  `syn_to_id` INT(19) NULL DEFAULT NULL,
  `word` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `syn_to_id` (`syn_to_id` ASC),
  CONSTRAINT `words_ibfk_1`
    FOREIGN KEY (`syn_to_id`)
    REFERENCES `ebdb`.`words` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
