-- MySQL Script generated by MySQL Workbench
-- 08/15/15 23:45:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chatbot_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatbot_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatbot_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `chatbot_test` ;

-- -----------------------------------------------------
-- Table `chatbot_test`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`topics` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `topic_name` VARCHAR(255) NOT NULL COMMENT '',
  `rank` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_TopicName` (`topic_name` ASC)  COMMENT '',
  INDEX `index_topic_name` USING BTREE (`topic_name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`rules` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `topic_id` INT(19) NULL DEFAULT NULL COMMENT '',
  `rule_name` VARCHAR(255) NOT NULL COMMENT '',
  `rank` INT(11) NULL DEFAULT NULL COMMENT '',
  `response` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_RuleName` (`topic_id` ASC, `rule_name` ASC)  COMMENT '',
  CONSTRAINT `rules_ibfk_1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `chatbot_test`.`topics` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`actions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `rule_id` INT(19) NULL DEFAULT NULL COMMENT '',
  `action_body` TEXT NOT NULL COMMENT '',
  `priority` INT(19) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `rule_id` (`rule_id` ASC)  COMMENT '',
  FULLTEXT INDEX `index_actions_action_body` (`action_body` ASC)  COMMENT '',
  CONSTRAINT `actions_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `chatbot_test`.`rules` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`chatbots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`chatbots` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `chatbot_name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_ChatbotName` (`chatbot_name` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`inputs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`inputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `rule_id` INT(19) NULL DEFAULT NULL COMMENT '',
  `input_text` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `rule_id` (`rule_id` ASC)  COMMENT '',
  CONSTRAINT `inputs_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `chatbot_test`.`rules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`outputs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`outputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `rule_id` INT(19) NULL DEFAULT NULL COMMENT '',
  `output_text` TEXT NOT NULL COMMENT '',
  `request` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `rule_id` (`rule_id` ASC)  COMMENT '',
  FULLTEXT INDEX `index_outputs` (`output_text` ASC)  COMMENT '',
  CONSTRAINT `outputs_ibfk_1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `chatbot_test`.`rules` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`queries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`queries` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `query_text` TEXT NOT NULL COMMENT '',
  `session_id` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `chatbot_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `event_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `response` TEXT NULL DEFAULT NULL COMMENT '',
  `actions` TEXT NULL DEFAULT NULL COMMENT '',
  `request` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `rule_id` INT(19) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `index_queries_session_chatbot` USING BTREE (`session_id` ASC, `chatbot_name` ASC)  COMMENT '',
  INDEX `index_queries_session` USING BTREE (`session_id` ASC)  COMMENT '',
  INDEX `index_queries_rule_id` USING BTREE (`rule_id` ASC)  COMMENT '',
  FULLTEXT INDEX `index_query_text` (`query_text` ASC)  COMMENT '',
  FULLTEXT INDEX `index_query_response` (`response` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`state_machines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`state_machines` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `state_machine_name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_StateMachineName` (`state_machine_name` ASC)  COMMENT '',
  INDEX `index_state_machine_name` USING BTREE (`state_machine_name` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`sm_actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`sm_actions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `state_machine_id` INT(19) NOT NULL COMMENT '',
  `sm_action_name` VARCHAR(255) NOT NULL COMMENT '',
  `action_text` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_SMActionName` (`state_machine_id` ASC, `sm_action_name` ASC)  COMMENT '',
  CONSTRAINT `sm_actions_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `chatbot_test`.`state_machines` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`sm_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`sm_rules` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `state_machine_id` INT(19) NOT NULL COMMENT '',
  `sm_rule_name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_SMRuleName` (`state_machine_id` ASC, `sm_rule_name` ASC)  COMMENT '',
  CONSTRAINT `sm_rules_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `chatbot_test`.`state_machines` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`sm_variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`sm_variables` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `state_machine_id` INT(19) NOT NULL COMMENT '',
  `sm_variable_name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_SMVariableName` (`state_machine_id` ASC, `sm_variable_name` ASC)  COMMENT '',
  CONSTRAINT `sm_variables_ibfk_1`
    FOREIGN KEY (`state_machine_id`)
    REFERENCES `chatbot_test`.`state_machines` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`sm_conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`sm_conditions` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `sm_rule_id` INT(19) NOT NULL COMMENT '',
  `sm_variable_id` INT(19) NOT NULL COMMENT '',
  `sm_variable_value` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_SMConditionName` (`sm_rule_id` ASC, `sm_variable_id` ASC)  COMMENT '',
  INDEX `index_sm_conditions_matching` USING BTREE (`sm_variable_id` ASC, `sm_variable_value` ASC)  COMMENT '',
  CONSTRAINT `sm_conditions_ibfk_1`
    FOREIGN KEY (`sm_rule_id`)
    REFERENCES `chatbot_test`.`sm_rules` (`id`),
  CONSTRAINT `sm_conditions_ibfk_2`
    FOREIGN KEY (`sm_variable_id`)
    REFERENCES `chatbot_test`.`sm_variables` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`sm_memory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`sm_memory` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `session_id` VARCHAR(255) NOT NULL COMMENT '',
  `state_machine_id` INT(19) NOT NULL COMMENT '',
  `sm_variable_name` VARCHAR(255) NOT NULL COMMENT '',
  `sm_variable_value` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `sm_last_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `short_string_value` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `long_string_value` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `uc_SMMemoryRecord` (`session_id` ASC, `state_machine_id` ASC, `sm_variable_name` ASC)  COMMENT '',
  INDEX `index_sm_memory_matching` USING BTREE (`session_id` ASC, `state_machine_id` ASC, `sm_variable_name` ASC, `sm_variable_value` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`split_inputs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`split_inputs` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `input_id` INT(19) NOT NULL COMMENT '',
  `prev_word` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `word` VARCHAR(255) NOT NULL COMMENT '',
  `next_word` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `index_split_inputs_InputID` USING BTREE (`input_id` ASC)  COMMENT '',
  INDEX `index_split_inputs_word_word` USING BTREE (`word` ASC)  COMMENT '',
  INDEX `index_split_inputs_word_triplet` USING BTREE (`prev_word` ASC, `word` ASC, `next_word` ASC)  COMMENT '',
  CONSTRAINT `split_inputs_ibfk_1`
    FOREIGN KEY (`input_id`)
    REFERENCES `chatbot_test`.`inputs` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`split_queries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`split_queries` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `query_id` INT(19) NULL DEFAULT NULL COMMENT '',
  `prev_word` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `word` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `next_word` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `query_id` (`query_id` ASC)  COMMENT '',
  CONSTRAINT `split_queries_ibfk_1`
    FOREIGN KEY (`query_id`)
    REFERENCES `chatbot_test`.`queries` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`topics_chatbots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`topics_chatbots` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `topic_id` INT(19) NOT NULL COMMENT '',
  `chatbot_id` INT(19) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `topic_id` (`topic_id` ASC)  COMMENT '',
  INDEX `chatbot_id` (`chatbot_id` ASC)  COMMENT '',
  CONSTRAINT `topics_chatbots_ibfk_1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `chatbot_test`.`topics` (`id`),
  CONSTRAINT `topics_chatbots_ibfk_2`
    FOREIGN KEY (`chatbot_id`)
    REFERENCES `chatbot_test`.`chatbots` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chatbot_test`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbot_test`.`words` (
  `id` INT(19) NOT NULL AUTO_INCREMENT COMMENT '',
  `syn_to_id` INT(19) NULL DEFAULT NULL COMMENT '',
  `word` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `syn_to_id` (`syn_to_id` ASC)  COMMENT '',
  CONSTRAINT `words_ibfk_1`
    FOREIGN KEY (`syn_to_id`)
    REFERENCES `chatbot_test`.`words` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
